---
version: 2
jobs:
  build:
    docker:
      - image: samuela/research-ci

    steps:
      # The mujoco key is kept as a base64 encoded secret in circleci.
      - run: echo $MUJOCO_LICENSE_KEY | base64 --decode > ~/.mujoco/mjkey.txt

      - checkout
      - restore_cache:
          key: deps-{{ checksum "Pipfile.lock" }}
      - run: pipenv install --dev
      - save_cache:
          key: deps-{{ checksum "Pipfile.lock" }}
          paths:
            - "/home/circleci/.local/share/virtualenvs/"
      - run:
          name: pyre
          command: pipenv run pyre --search-path=$(pipenv --venv)/lib/python3.7/site-packages/ check
      - run:
          name: pylint
          command: pipenv run pylint research
      - run:
          name: yapf
          command: pipenv run yapf --exclude "**/.*" --diff --recursive .
